### ISSUE TITLE
Connection closed before receiving a handshake response

### ISSUE THREAD

**Issue by stemuk** [deepstreamIO/deepstream.io-tools-polymer#1]
It seems like the deepstream.io polymer element does not work correctly together with the deepstream js client. <br>
Every time I initialize the connection through 
`<ds-connection
  				url="localhost:6020"
  				state="{{connectionState}}"
  				ds={{ds}}>
  			</ds-connection>` 
the console puts out these issues:

![image](https://cloud.githubusercontent.com/assets/17005007/19943030/11c1595a-a136-11e6-9c7a-4d1a9f74da1e.png)

The basic connection to the deepstream server seems to work so far, but as far as I get it the websocket handshake doesn't happen. This only seems to be the case when I use the Polymer elements, the regular js client works fine. As a test I tried out the ds-tutorial-polymer, which didn't work either.<br> I would really appreciate it if somebody could address this issue, it basically makes all the nice deepstream Polymer components useless.

Thanks in advance,
Stefan

**Comment by yasserf** [comment]
Which deepstream server version you using?

**Comment by stemuk** [comment]
The 1.1.1 version, but I was expecting the error to be on the client side, since the vanilla js client works fine.

**Comment by stemuk** [comment]
Were you able to reproduce the issue with ds-tutorial polymer or is it just a bad configuration on my side?

**Comment by yasserf** [comment]
I haven't yet tried tbh, I'll take a look as soon as i get some time later today and let you know.

**Comment by stemuk** [comment]
The update to the latest ds version didn't fix the issue btw, is there a way to go back in time and test it with a deepstream version < 1.0?

**Comment by stemuk** [comment]
Somehow it works right now, looks like I screwed it up. Sorry! :D

**Comment by yasserf** [comment]
No worries, happy it worked out, and sorry I didn't get the time to look at it!
